version: '3.6'

services:
  lyfilifedb:
    container_name: lyfilifedb
    image: postgres:11.13
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YourStrongPassw0rd
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  flyway:
    container_name: lyfilife_flyway
    build:
      context: .
      dockerfile: Docker/PostgresMigrations.Dockerfile
    command: -url=jdbc:postgresql://lyfilifedb:5432/postgres -locations='filesystem:/flyway/sql/' -schemas=public -user=postgres -password=YourStrongPassw0rd -connectRetries=10 migrate info
    volumes:
      - .:/flyway/sql
    depends_on:
      - lyfilifedb

volumes:
  pgdata:
  security:

